### ISSUE TITLE
Bobler vedr. GDPR

### ISSUE THREAD

**Issue by ClockEnd** [ballerupgis/SeMaWi#229]
Såvidt jeg har forstået en af de centrale opgaver if Persondataforordningen, så er det en fortegnelse over behandlingsaktiviteter med hjemmel i noget faglovgivning. Her kunne det være en løsning at oprette fortegnelsen i wiki med hjemmel via KLE.
En fortegnelse kunne være:
* Navn og kontaktinformation på den dataansvarlige og DPO'en (Data Protection Officer)
* Beskrivelse af formålet med behandlingen
* Beskrivelse af kategorier af registrerede, personoplysninger og evt. modtagere.
* Periode for behandling samt hvis det er muligt, de forventede tidsfrister for sletning af de forskellige 
   kategorier af oplysninger
* Hvis det er muligt, en generel beskrivelse af de tekniske og organisatoriske sikkerhedstiltag
Dette erstatter i øvrigt den hidtidige anmeldelsespligt, og hvis man allerede har lavet anmeldelser til Datatilsynet, kan disse i vidt omfang genbruges som fortegnelser over behandlingsaktiviteter.
Og rolig nu, jeg har ikke været klog men bare sakset noget sammen

**Comment by ClockEnd** [comment]
Vi opdeler Kategorien: Data i to tabs, et med GDPR og en med STORM (rammearkitektur).
GDPR:
* Navn
*GDPR (flueben j/n) tilføjes
*Beskrivelse
*Bestiller
*Modtager
*Dataansvarlig
*DPO-navn
*KLEnr
*Startdato for dataindsamling
*Slutdato for databearbejdning
*Tilgængelighed (her beskrives sikkerhedstiltag, sletningstidsfrister - egne og modtagers?)
*Personidentifikation (laves som kombobox der kan indeholde flere værdier)

*Registertype FLYTTES til STORMfanen
*Stormopmærking FLYTTES til STORMfanen
*Opdateringsfrekvens FLYTTES til STORMfanen
*Rammearkitekturbyggeklods FLYTTES til STORMfanen
*Kritikalitet FLYTTES til STORMfanen
*Fortrolighed FLYTTES til STORMfanen
*Integritet FLYTTES til STORMfanen
*Originalitet FLYTTES til STORMfanen
*Geografisk identifikation FLYTTES til STORMfanen
*Geodatarelation FLYTTES til STORMfanen

**Comment by ClockEnd** [comment]
**Hjemmelsspørgsmålet**
Indtil videre (KL kommer med et udspil senere) fx
Typer   af behandlings hjemler
--
* Samtykke
* Behandlingen er nødvendig for at   opfylde en kontrakt, som den registrerede er part i* eller for at gennemføre foranstaltninger   forud for indgåelse af en sådan kontrakt, som den registrerede har bedt om.
Behandlingen er nødvendig for at   overholde en retlig forpligtelse.
Behandlingen er nødvendig for at   beskytte vitale interesser
Behandlingen er nødvendig for at   udføre en opgave i samfundets interesse
Behandlingen er nødvendig for at   udføre en opgave, som henhører under offentlig myndighedsudøvelse
Behandlingen er nødvendig for at   forfølge legitime interesser, og den registreredes interesser går ikke forud herfor
Ingen hjemmel
Ved ikke

**Comment by baffioso** [comment]
Tilføj dataansvarlig

**Comment by ClockEnd** [comment]
Glimrende
