### ISSUE TITLE
Få nyeste version af SeMaWi op at køre lokalt vha. docker compose

### ISSUE THREAD

**Issue by baffioso** [ballerupgis/SeMaWi#234]
Første skridt i at opgradere til nyeste version af SeMaWi, hvor applikationen køres vha. docker compose er at få den til at kører lokalt. Se evt #194 for tanker omkring.

**Comment by adam42-dk** [comment]
hvis vi antager, at nyeste version er 2017_01, så er der mindst to issues i den version, der skal laves før vi kan få den op og køre as-it-is:

- Når man kører kommandoen "docker-compose up -d" vil der blive bygget tre images (debian, mysql og semawi). Det ser ud til at køre fint lige undtagen, at docker-compose.yml ikke synes, at ramme Dockerfile. Derfor bliver host filen plus alle de andre elementer ikke aktiveret i containeren - dette skal laves.
- Filer i "mutables"-mappen bliver ikke kopieret til mappen /srv/semawi - de bliver kun oprettet som mapper. Dette skal laves om, så man får filerne til, at rette i når man har kørt kommandoen.

**Comment by adam42-dk** [comment]
@JosefAssad Jeg kørt **docker-compose up -d** og får til sidst i loggen ved en kørsel af **docker-compose logs** følgende fejl, der refererer til Aache2:

`semawi-mediawiki | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message`

ServerName / hostname sættes vel i docker-compose.yml i linje 25 "hostname: semawi-mediawiki" ?

Jeg har forsøgt med følgende kode stump til Dockerfile:

```
echo "ServerName semawi-mediawiki" | tee /etc/apache2/conf-available/servernanme.conf
a2enconf servername.conf
service apache2 reload
```	

giver responsen

[FAIL] Reloading web server: apache2 failed!
[warn] Apache2 is not running ... (warning).


Og loggen giver:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
[mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
[core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

... og i /etc/hostname er semawi-mediawiki og /etc/hosts er:

127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.18.0.3      semawi-mediawiki

... nogen forslag til hvordan jeg får det til at køre med 001-semawi enabled på localhost ?

**Comment by JosefAssad** [comment]
svjh er den specifikke fejlbesked fra Apache ikke noget der skulle forhindre SeMaWi i at komme op og køre korrekt. :)

**Comment by adam42-dk** [comment]
@JosefAssad  jo jo, SeMaWi kommer op og køre, men a2disite 000-default og a2ensite 001-semawi slår ikke igennem. Det er dér problemet ligger.

**Comment by adam42-dk** [comment]
@JosefAssad 
Nå... men jeg fik sat 000-default af virtualhost og 001-semawi på - det skulle skulle ske Dockerfile i stedet for entrypoint.

Problemet, der nu er der, når jeg forsøger at se wiki'en i browseren, har noget med GraphViz-udvidelsen. Fejlen fra apache loggen:

 [:error] [pid 600] [client 172.18.0.1:50260] PHP Fatal error:  Uncaught exception 'Exception' with message '/var/www/wiki/extensions/GraphViz/extension.json: unsupported manifest_version: 2' in /var/www/wiki/includes/registration/ExtensionRegistry.php:195\nStack trace:\n#0 /var/www/wiki/includes/registration/ExtensionRegistry.php(137): ExtensionRegistry->readFromQueue(Array)\n#1 /var/www/wiki/includes/Setup.php(39): ExtensionRegistry->loadFromQueue()\n#2 /var/www/wiki/includes/WebStart.php(137): require_once('/var/www/wiki/i...')\n#3 /var/www/wiki/index.php(40): require('/var/www/wiki/i...')\n#4 {main}\n  thrown in /var/www/wiki/includes/registration/ExtensionRegistry.php on line 195

Jeg kan ikke rigtig finde en løsning - har du Josef stødt på den fejl før?

**Comment by fadeto404** [comment]
@adam42-dk 
Det er måske et skud i tågen prøv at åbne `/var/www/wiki/extensions/GraphViz/extension.json` og skift `manifest_version` til 1. Hvis det hjælper kan det være en god ide at finde ud af om udvidelsen stadig virker.

Læs evt.:
https://www.mediawiki.org/wiki/Manual:Extension.json/Schema#manifest_version

**Comment by adam42-dk** [comment]
Tak, @fadeto404  det vil jeg forsøge med. Hvis det ikke virker må vi finde ud af om der findes et alternativ til den.

**Comment by adam42-dk** [comment]
Ok. så fik jeg SeMaWi version 2017_01 at køre, lokalt. Der var nogle ting der skulle flytte og tilføjes. 

De er nu blevet push'et til Origin/Master gren.
