### ISSUE TITLE
"dev" overtager DNS på internserver

### ISSUE THREAD

**Issue by baffioso** [ballerupgis/SeMaWi#238]
@adam42-dk vi oplever nu at vi bliver omdirigeret til `http://dev.wiki/index.php/Forside` når vi går ind på vores `wiki/` DNS. Har måske noget at gøre med #236

**Comment by adam42-dk** [comment]
@baffioso nu er fejlen rettet. Det var mig, der havde rettet en url i en LocalSettings.php for den forkerte docker-concaiter. /Facepalm/

**Comment by baffioso** [comment]
@adam42-dk Vi har haft problemer med serveren og den er blevet genstartet og har startet semawi docker containeren. Vi oplever igen at DNS opfører sig lidt sjovt og da den peger på 10.192.224.40:4321  istedet for 10.192.224.40:12345. Vi ikke helt om det har relation til dette issue.

**Comment by adam42-dk** [comment]
Oh. Det er sommervarmen, der har sat sig på hjernen... jeg fikser den når jeg er på pc igen. #sry

**Comment by baffioso** [comment]
Jo, det er i den config det skal opsættes, men det kræver at IT forsyning opretter en DNS som vi kan bruge. Jeg tænker at vi i første omgang ikke behøver en DNS, eftersom som vi pt. blot er 4-5 personer som skal tilgå udviklingsversionen og vi derfor bare bruger en grim url.

**Comment by adam42-dk** [comment]
Ja, vi kan sagtens bruge den grimme url, men noget gør at den ikke kan tilgås. Man får en adgangsfelj når besøger adressen.

**Comment by adam42-dk** [comment]
@baffioso kan vi lukke det her issue ? :)

**Comment by baffioso** [comment]
Yes
