### ISSUE TITLE
Upload af filer virker ikke

### ISSUE THREAD

**Issue by ArtificialTruth** [ballerupgis/SeMaWi#239]
Når man uploader en opdatereret version af en fil eller en ny via http://wiki/index.php/Speciel:Upload 
lykkes det ikke, og denne fejl dukker op:

	Warning: fopen(/var/www/wiki/images/lockdir/j5xrffde05wfz6m2yf0jtmv1exvrtyk.lock): failed to open stream: Permission denied in /var/www/wiki/includes/filebackend/lockmanager/FSLockManager.php on line 125
	Exception encountered, of type "LocalFileLockError"

**Comment by adam42-dk** [comment]
Hej @ArtificialTruth - jeg har nu sat en variabel ind i filen, der styrer de lokale indstillinger, som gerne skulle løse din udfordring. Kan jeg få dig til, at uploade filen igen og melde tilbage her om det har løst det eller ej?

@fadeto404 : problemet er opstået - formoder jeg - fordi variablen $wgTransactionalTimeLimit ikke var sat i filen /srv/semawiLocalSettings.php. Når den ikke er sat vil der ikke være en begrænsning på tiden, og det vil skabe en konflikt, fordi den er sat højere end variablen max_execution_time (i /srv/semawi/php.ini) - den sidste er sat til 30 sekunder, så $wgTransactionalTimeLimit er sat til 25, da den skal være lavere end max_execution_time. 
se REF: https://www.mediawiki.org/wiki/Topic:Thw9ec1z240n06d8

**Comment by fadeto404** [comment]
Godt at vide. De 25 sekunder bør være nok til de fleste operationer, så vi holder den bare der indtil videre.

**Comment by JosefAssad** [comment]
Ah, hvis ikke det hjælper så kan i også kigge på file and directory permissions på images og underfoldere. Vi har set noget lignende før da images er en volume mount ind i containeren hvilket kan forvirre permissions billedet lidt.

**Comment by ArtificialTruth** [comment]
Får stadig denne:

    Warning: fopen(/var/www/wiki/images/lockdir/j5xrffde05wfz6m2yf0jtmv1exvrtyk.lock): failed to open stream: Permission denied in /var/www/wiki/includes/filebackend/lockmanager/FSLockManager.php on line 125
    Exception encountered, of type "LocalFileLockError"

**Comment by adam42-dk** [comment]
@JosefAssad det var også min første indskydelse... tjekkede det og så at /srv/semawi/images havde de rette ejer:gruppe indstillinger, men... det var ikke ført helt igennem til alle undermapper og filerne i disse. Det har jeg nu lavet om, så det er www-data:www-data i stedet for root:root. 

@ArtificialTruth kan jeg få dig til at forsøge igen asap ?

**Comment by ArtificialTruth** [comment]
Hej @adam42-dk
Jeg får stadig samme fejl. Får du samme fejl hvis du hopper på wiki via VPN?

**Comment by adam42-dk** [comment]
Jeg har ikke forsøgt...  har rettet fejlen, som andre før os har haft den, og bedt dig om at teste den... har du @fadeto404 en testside som jeg kan uploade en tom text fil til ?

**Comment by adam42-dk** [comment]
ok. kigger på det i aften eller i weekenden :)

**Comment by ArtificialTruth** [comment]
Kan bekræfte at det virker her :+1:

**Comment by ArtificialTruth** [comment]
Nu får jeg fejl igen.

**Comment by adam42-dk** [comment]
@ArtificialTruth ... alle underliggende filer og mapper i /var/www/images/ (i docker container) havde ændret ejerskab fra www-data:www-data til root:root - derfor fik du fejlen igen.

Jeg tænker, at løsningen kunne være et cron job, der tjekker hvilke ejerskabsattributter /var/www/images har. Hvad siger du til den lille opgave @fadeto404 ? Den store udfordring her er, at det skal sættes op i containeren.

**Comment by fadeto404** [comment]
Jeg skal lige have adgang til serveren, så kan jeg godt sætte det op.

**Comment by baffioso** [comment]
Er det en robust løsning at opsætte cronjob inde i containere? Hvis det er den eneste løsning, skal vi nok overveje at få det ind i dockerfilen.

**Comment by JosefAssad** [comment]
Lidt backseat driving herfra:

Det er overraskende besværligt at køre et cronjob i en docker container. Been there got the t-shirt etc. etc. Årsagen er, at det er meningen at en docker container == 1 process. Det kan måske virke som en lidt underlig begrænsning, og man kan sagtens kode sig ud af den, men det er tiltænkt større og mere komplekse applikationsarkitekturer med mange services der skal interagere.

Det er derfor for eksempel at gc2 sync kører som batch job, triggered fra et cronjob på docker host, ikke fra docker containeren. Hvis cron skal køre fra en container, så er det fra SeMaWi containeren, i hvilket tilfælde der pludselig skal køre TO processer (apache og cron) ikke en (apache). Og så skal det hele køre indirekte via en process supervisor ([supervisord](http://supervisord.org/) er ret populær) eller via noget Dr. Frankenstein-agtigt via systemd.

Hvis den docker mount i /var/www/images skifter ejer hele tiden så er det nok værd at undersøge hvorfor det sker, det tror jeg ikke et cronjob vil fortælle noget om; det kan evt. være der er noget/nogen som genstarter docker daemon?

**Comment by JosefAssad** [comment]
En ting som i måske kan undersøge er docker named volumes/`docker volume create`. Hvis i kan få det til at spille sammen med semawi containerens permissions/ownership verdensbillede så er det bedre end det der er i dag.

**Comment by adam42-dk** [comment]
@JosefAssad Tak for dine indspark! Altid godt, at have nogle med på backseat-driving positionen :)

Det jeg har fundet frem til er, der skal sættes en cronjob fil klar i kulissen og sættes op på Volumes, en linje med ADD, RUN, RUN og CMD i Docker filen ala >> https://www.ekito.fr/people/run-a-cron-job-with-docker/

Ville det ikke være et "fornuftigt" hack på denne (nye?) udfordring?  & selvfølgelig det ikke skal være permanent; jeg regner ikke med, at overføre til det nye SeMaWi setup.

docker volume create har jeg kigget på, det ser ud til, at det er Løsningen på den lange bane.

**Comment by adam42-dk** [comment]
@ArtificialTruth  ja, og det var lavet. det har virket indtil wiki'en blev genstartet. og nu virker det igen. 

@JosefAssad hvordan ville du sætte de to meget enkelte (hack-)commands op i din runcontainer.sh ?

**Comment by ArtificialTruth** [comment]
@adam42-dk Ah det var uheldigt, men mange tak for hjælpen.

**Comment by JosefAssad** [comment]
> @JosefAssad hvordan ville du sætte de to meget enkelte (hack-)commands op i din runcontainer.sh ?

Well. Forudsat vi er overbevist at problemet er permissions på en docker volume mount, så ville jeg være nysgerrig hvorfor de ændrer sig. Hvis permissions på `images/` skal være `www-data:www-data` og hvis vi *VED* vi har skiftet det med `chmod -R` (bemærk `-R`) og hvis vi så senere opdager noget har flyttet det tilbage til root:root så ville jeg gerne vide hvilke process er ansvarlig for det.

Med andre ord, root cause analysis. :) Giver det mening?

**Comment by adam42-dk** [comment]
Hej @JosefAssad  & @fadeto404 ja, jeg er nysgerrig på, hvad og hvornår ownership ændres tilbage til root:root. Derfor har jeg testet en auditd opsætning op egen servere og fundet, at det var dét der skal til for, at løse mysteriet. Men... som du jo ved, så er Ballerup Kommunes regler om VPN-adgang, ja.. strikse. Så lige afventer jeg at få fornyet min adgang.

Indtil da... @fadeto404  har du fået adgang til serveren ? Hvis, ja så vil jeg gerne bede dig om at sætte det op og lave et cronjob, der sender med en e-mail med audit.log til mig hver dag kl. 9. Kan jeg få dig til det ?

**Comment by JosefAssad** [comment]
Bare helt lavpraktisk, kan det være der er noget som genstarter containeren/docker.service og dermed resetter ownership?

**Comment by adam42-dk** [comment]
@JosefAssad ja, det var det det skete sidst docker containeren blev genstartet. En løsning er måske den som findes i den her stackoverflow-tråd » https://stackoverflow.com/questions/28879364/docker-copy-and-change-owner (?)

**Comment by adam42-dk** [comment]
Løsningen blev at der blev sat et rekursivt ejerskab på images-mappen til brugeren www-data.

Se >> [commit](https://github.com/ballerupgis/SeMaWi/commit/6e52bc14f22c78442b75da14b04db6834e0a89b0)
