### ISSUE TITLE
IP-adressen for dev-semawi-mediawiki stemmer ikke ...

### ISSUE THREAD

**Issue by adam42-dk** [ballerupgis/SeMaWi#242]
@fadeto404 - der er noget, der ikke stemmer overens med adressen jeg sætter vores dev af SeMaWi op på, og så den som bliver automatisk skrevet ind i /etc/hosts/

IP-adresserne er forskellige (jeg skriver dem selvfølge ikke her, men sender dem separat i en mail til dig)

Kan jeg få dig til, at undersøge hvordan det spiller sammen ? Hvilken adressen kan jeg tilgå dev-Semawi-mediawiki fra ?

**Comment by fadeto404** [comment]
Jeg undersøger sagen.

**Comment by fadeto404** [comment]
Adressen 10.X.X.X er selve produktionsserverens IP. Så vidt jeg ved har hver docker-container sin egen IP-adresse, hvilket er den adresse du ser med 172.X.X.X

Når du skal tilgå wikien skal det nok være på 10.X.X.X:xxxx som du sendte mig. Containerens IP bliver kun brugt internt af containeren selv. Man skal bare sørge for at mappe portene på hosten og containeren så de passer, hvilket det ikke ser ud til at de er lige nu.

**Comment by JosefAssad** [comment]
Og `$wgServer` i `LocalSettings.php` skal være wiki'ens *eksterne* addresse. Lært i "school of hard knocks". :)

**Comment by adam42-dk** [comment]
@fadeto404 ok. portene skulle gerne være mappet 1:1. Hvor ser du, at det ikke passer ?

@JosefAssad *tjek* $wgServer er sat til ip'en:port

**Comment by fadeto404** [comment]
Lukker det da containeren er fjernet
